version: 0.0
os: linux
files:
  - source: /
    destination: /home/work/app
    file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deploy/stop_app.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_app.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy/healthcheck.sh
      timeout: 300
      runas: root
